OBJECTS = arrayStack derivedArrayStackWithCatch  hanoiRecursive    linkedStack  parenthesisMatching  switchBox \
derivedArrayStack  equivalenceClasses          hanoiUsingStacks  maze         railroadWithStacks

all: $(OBJECTS)

