allObjects = abcInt abcFloat abcTemplate abcRef \
	abcConstRef abcGeneral noSwap abcExceptionChar \
	make2dArray make2dArrayNoCatch delete2dArray \
	currency currencyNew currencyOverload currencyFriend \
	abcException factorial sum rsum \
	permutations sumSTL productSTL permutationsSTL \
	quadraticRoots indexOfMax 

all: $(allObjects) 


# to read -> permutation, sumSTL, productSTL (operator), permutationSTL, 
