allObjects = sequentialSearch1 rSequentialSearch polyEval \
	horner rank rankSort1 selectionSort bubbleSort \
	insert rankSort2 earlySelectionSort earlyBubbleSort \
	insertionSort1 insertionSort2 sumCount1 sumCount2 \
	rSumCount matrixTranspose inef matrixAdd \
	matrixMultiply1 matrixMultiply2 minmax1 minmax2 \
	sequentialSearch2 d 

all: $(allObjects) 

